/*
 * ----------------------------------------------------
 * Automatically generated by VerBuild 2.0.605.0.
 * Do not edit by hand.
 * ----------------------------------------------------
 */

#pragma once

#ifndef __VersionInfo_Header__
#define __VersionInfo_Header__

/**
 * @file I:\Prj\My\ExceptEngine\Build\vs2017\../../Src/Res/VersionNo.h
 * @author Verbuild 2.0.605.0
 * @brief Provides version information.
 */

/**
 * @def EXCEPTENGINE_VERSION_MAJOR
 * @brief Major version number.
 *
 * @def EXCEPTENGINE_VERSION_MINOR
 * @brief Minoir version number.
 *
 * @def EXCEPTENGINE_VERSION_BUILD
 * @brief Build number.
 *
 * @def EXCEPTENGINE_VERSION_PPATCH
 * @brief Patch number.
 *
 * @def EXCEPTENGINE_VERSION_BASE_YEAR
 * @brief The year the project was started.
 *
 * @def EXCEPTENGINE_VERSION_DATE
 * @brief The date this build was compiled.
 *
 * @def EXCEPTENGINE_VERSION_TIME
 * @brief The time this build was compiled.
 *
 * @def EXCEPTENGINE_VERSION_STRING
 * @brief String representation of the version.
 */
#define EXCEPTENGINE_VERSION_MAJOR      0
#define EXCEPTENGINE_VERSION_MINOR      0
#define EXCEPTENGINE_VERSION_BUILD      20180613
#define EXCEPTENGINE_VERSION_PATCH      7

#define EXCEPTENGINE_VERSION_BASE_YEAR  2018
#define EXCEPTENGINE_VERSION_DATE       "2018-Jun-13"
#define EXCEPTENGINE_VERSION_TIME       "00:07:52"
#define EXCEPTENGINE_VERSION_STRING     "0.0.20180613.7"

/**
 * @Brief Version number structure.
 *
 * @var baseYear
 * @brief The year the project was started.
 *
 * @var major
 * @brief Major version number.
 *
 * @var minor
 * @brief Minor version number.
 *
 * @var build
 * @brief Build number.
 *
 * @var patch
 * @brief Patch number.
 */
static struct ExceptEngine_VersionNumber_s {
    int baseYear;
    int major;
    int minor;
    int build;
    int patch;
} ExceptEngine_VersionNumber = {
    2018,
    0,
    0,
    20180613,
    7
};

#endif // !__VersionInfo_Header__
